apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "templating-deep-dive.fullname" . }}
  labels: {{ include "templating-deep-dive.selectorLabels" . | nindent 4 }}    
spec:
  replicas: {{- if eq .Values.environment "production" }} {{ .Values.replicaCount }} {{- else -}} 2 {{- end }}
  selector:
    matchLabels: {{ include "templating-deep-dive.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "templating-deep-dive.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          {{- /* If .Values.services has a length greater than 0, use it. Otherwise use an empty list. */}}
          {{- /* This line is important so that we don't run into null pointer errors. */}}
          {{- /* If empty list, do not expose port */}}
          {{- if .Values.services | default dict | len }}
          ports:
            - containerPort: {{ .Values.containerPorts.http }}
          {{- end }}