## @param customName allows to set a custom resource name for the K8s resources in the chart.
##        Defaults to {{ .Release.Name }}-{{ .Chart.Name }}
customName: ''

## @param replicaCount Number of Nginx replicas to deploy
replicaCount: 3

## Settings for NGINX image
##
## @param image.name Nginx image name to use
## @param image.tag Nginx image tag to use
image:
  name: nginx
  tag: '1.27.0'

## Settings for NGINX container securityContext
##
## @param securityContext.enabled
## @param securityContext.runAsUser
## @param securityContext.fsGroup
securityContext:
  enabled: true
  runAsUser: 1000
  fsGroup: 2000

## NGINX container ports
##
## @param containerPorts.http
containerPorts:
  http: 80

## Settings for NGINX services
## services is a map with the following schema
##
## @param services["*"].type The type of service in front of the Nginx pods
## @param services["*"].port The port where the service is receiving requests
services:
  svc1:
    type: ClusterIP
    port: 80
  svc2:
    type: NodePort
    port: 30007