## @param customName allows to set a custom resource name
## Defaults to {{ .Release.Name }}-{{ .Chart.Name }}
customName: ''

## @param replicaCount: Number of Nginx replicas to deploy
replicaCount: 3
environment: production

## Settings for Nginx image
image:
  name: nginx
  tag: "1.29.4"

## NGINX container ports
containerPorts:
  http: 80

## Services is a map witht he following schema
services:
  svc1:  
    type: ClusterIP
    port: 80
  svc2:
    type: NodePort
    port: 30007